name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

      - name: SonarQube Analysis
        run: mvn sonar:sonar
deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy into Server
      run: echo "Deploying into Server"
notifications:
  runs-on: ubuntu-latest
  needs: deploy
  if: always()
  steps:
    - name: Notify Agents
      run: echo "Sending message to agent"
