pipeline {
    agent any
    tools {
        maven '3.9.4'
    }
    stages {
        stage("Source") {
            steps {
                git branch: 'main', url: 'https://github.com/tonux/demo-test-sir.git'
            }
        }
        stage("Build") {
            steps {
                sh 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install'
            }
        }
        stage("SonarQube AnalC:\\Users\\hp\\Desktop\\Cours M1SIR\\Genie Logiciel\\tp-master-sir-2023ysis") {
            steps {
                sh 'mvn sonar:sonar'
            }
        }
        stage('Approve Deployment') {
            input {
                message "Do you want to proceed for deployment?"
            }
            steps {
                sh 'echo "Deploying into Server"'
            }
        }
    }
    post {
        aborted {
            echo "Sending message to agent"
        }
        failure {
            echo "Sending message to agent"
        }
        success {
            echo "Sending message to agent"
        }
    }
}
